import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import NavBar from "@/modules/navbar";
import Clock from "@/modules/clock";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aman Pal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="md:fixed lg:fixed absolute z-50 right-0">
          <Clock />
        </div>
        <div className="md:fixed lg:fixed fixed z-50 flex md:right-0 lg:right-0 items-center bottom-0 lg:justify-end md:justify-end w-full lg:w-auto md:w-auto justify-center lg:min-h-screen md:min-h-screen">
          <NavBar />
        </div>
        <div className="mb-24 md:mb-0 lg:mb-0">
          {children}
        </div>
      </body>
    </html>
  );
}
